openapi: 3.0.3
info:
  title: 구인구직C Ver7.0 (Modernized API)
  description: 레거시 '구인구직C Ver6.2'를 2025년 표준(Headless, API-First, JWT, RBAC)으로 현대화한
    API 명세서입니다.
  version: 1.0.0
  license:
    name: UNLICENSED
    url: https://github.com/esl365/jobboard-spec-suite
servers:
  - url: /api/v1
    description: 메인 API v1 서버
components:
  securitySchemes:
    jwtBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 로그인 시 발급되는 AccessToken (JWT)
  schemas:
    UserMinimal:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        email:
          type: string
          format: email
          example: company@example.com
        user_type:
          type: string
          enum:
            - PERSONAL
            - COMPANY
            - ADMIN
          example: COMPANY
    UserLoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    UserLoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJ...
        refreshToken:
          type: string
          example: eyJ...
        user:
          $ref: "#/components/schemas/UserMinimal"
    JobCreateRequest:
      type: object
      required:
        - title
        - description
        - expires_at
      properties:
        title:
          type: string
          example: 2025년 하반기 백엔드 개발자 모집
        description:
          type: string
          example: <p>공고 본문 (HTML 또는 JSON)</p>
        employment_type:
          type: string
          enum:
            - FULL_TIME
            - PART_TIME
            - CONTRACT
        salary_min:
          type: number
          example: 50000000
        expires_at:
          type: string
          format: date-time
          example: 2025-12-31T23:59:59Z
    JobSummary:
      type: object
      properties:
        job_id:
          type: integer
          example: 101
        title:
          type: string
          example: 2025년 하반기 백엔드 개발자 모집
        company_name:
          type: string
          example: (주)모던잡
        status:
          type: string
          enum:
            - DRAFT
            - ACTIVE
            - EXPIRED
          example: ACTIVE
        expires_at:
          type: string
          format: date-time
    JobDetail:
      allOf:
        - $ref: "#/components/schemas/JobSummary"
        - type: object
          properties:
            description:
              type: string
    OrderPrepareRequest:
      type: object
      required:
        - package_id
        - payment_method
      properties:
        package_id:
          type: integer
          example: 1
        payment_method:
          type: string
          enum:
            - CREDIT_CARD
            - TOSS_PAY
            - KAKAO_PAY
    OrderPrepareResponse:
      type: object
      properties:
        order_id:
          type: integer
          example: 5001
        total_amount:
          type: number
          example: 150000
        pg_request_payload:
          type: object
          description: Toss/Iamport 등 PG사에 전달할 결제 요청 페이로드
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: 요청 처리에 실패했습니다.
        code:
          type: string
          example: INVALID_INPUT
    Order:
      type: object
      required:
        - orderId
        - userId
        - status
        - totalAmountCents
      properties:
        orderId:
          type: string
        userId:
          type: string
        status:
          type: string
          enum:
            - PENDING
            - COMPLETED
            - FAILED
            - REFUNDED
        totalAmountCents:
          type: integer
        provider:
          type: string
        providerPaymentId:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    WebhookEvent:
      type: object
      required:
        - eventUid
        - provider
        - type
        - occurredAt
      properties:
        eventUid:
          type: string
          description: dedupe key
        provider:
          type: string
        type:
          type: string
          enum:
            - payment.completed
            - payment.failed
            - payment.refunded
        occurredAt:
          type: string
          format: date-time
        data:
          type: object
          additionalProperties: true
        signature:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
    HealthCheckResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum:
            - ok
          example: ok
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 형식의 현재 시각
          example: 2025-10-27T12:34:56.789Z
paths:
  /health:
    get:
      operationId: healthCheck
      security: []
      tags:
        - System
      summary: Health Check
      description: 서비스 상태를 확인합니다. 인증 불필요.
      responses:
        "200":
          description: 서비스 정상 작동
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResponse"
        "503":
          description: 서비스 이용 불가
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Service unavailable
  /auth/login:
    post:
      operationId: login
      security: []
      tags:
        - Auth
      summary: 사용자 로그인 (JWT 발급)
      description: 로그인 성공 시 AccessToken과 RefreshToken을 발급합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserLoginResponse"
        "401":
          description: 인증 실패 (이메일 또는 비밀번호 불일치)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /jobs:
    get:
      operationId: listJobs
      security: []
      tags:
        - Jobs
      summary: 채용 공고 목록 조회
      description: 필터링/검색/페이지네이션을 지원하는 공고 목록을 반환합니다. (HTML 조각이 아닌 JSON 데이터)
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: search_keyword
          in: query
          schema:
            type: string
      responses:
        "200":
          description: 공고 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                      current_page:
                        type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/JobSummary"
    post:
      operationId: createJob
      tags:
        - Jobs
      summary: 채K용 공고 등록
      description: "기업 회원('COMPANY' 타입)만 공고를 등록할 수 있습니다. (RBAC: 'job:create' 권한 필요)"
      security:
        - jwtBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobCreateRequest"
      responses:
        "201":
          description: 공고 등록 성공 (초안 또는 검수 대기 상태)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobDetail"
        "401":
          description: 인증되지 않은 사용자
        "403":
          description: "권한 없음 (예: 개인회원이 시도)"
  /jobs/{jobId}/apply:
    post:
      operationId: applyToJob
      tags:
        - Applications
      summary: 채용 공고에 지원
      description: "개인 회원('PERSONAL' 타입)만 공고에 지원할 수 있습니다. (RBAC: 'application:create'
        권한 필요)"
      security:
        - jwtBearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resume_id:
                  type: integer
                  description: 제출할 이력서 ID
      responses:
        "201":
          description: 지원 성공
        "403":
          description: "권한 없음 (예: 기업회원이 시도)"
        "409":
          description: 중복 지원 (Conflict)
  /orders/prepare:
    post:
      operationId: prepareOrder
      tags:
        - Payments
      summary: 결제 준비
      description: PG사(Toss, Iamport) 결제창을 띄우기 전, 서버에 주문 정보를 생성하고 결제 요청 데이터를 받습니다.
      security:
        - jwtBearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderPrepareRequest"
      responses:
        "200":
          description: 결제 준비 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderPrepareResponse"
  /orders/webhook:
    post:
      operationId: handleOrderWebhook
      security: []
      tags:
        - Payments
      summary: 결제 완료 웹훅 (PG사 호출)
      description: PG사(Toss, Iamport)가 결제 승인/실패 결과를 이 엔드포인트로 전송합니다. (인증 없음)
      requestBody:
        description: PG사 고유의 웹훅 페이로드
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: 웹훅 처리 성공 (결제 완료 및 포인트/상품 지급 처리)
        "400":
          description: 잘못된 요청 또는 위변조 시도
  /payments/prepare:
    post:
      operationId: preparePayment
      summary: Create/ensure an order (idempotent by Idempotency-Key)
      security:
        - jwtBearerAuth: []
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
            minLength: 8
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - amountCents
                - provider
              properties:
                userId:
                  type: string
                amountCents:
                  type: integer
                  minimum: 0
                provider:
                  type: string
                  example: mock
                packageId:
                  type: string
                  nullable: true
      responses:
        "200":
          description: ensured
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "409":
          description: idempotency collision
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /webhooks/payments/{provider}:
    post:
      operationId: handlePaymentWebhook
      summary: Provider webhook (exactly-once)
      security: []
      parameters:
        - in: path
          name: provider
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebhookEvent"
      responses:
        "200":
          description: accepted (even on replay)
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
        "400":
          description: bad signature/payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
