diff --git a/db/_legacy/schema.core.sql b/db/_legacy/schema.core.sql
new file mode 100644
index 0000000000000000000000000000000000000000..264b3466217c14d70244c080784833c1d083f0e6
--- /dev/null
+++ b/db/_legacy/schema.core.sql
@@ -0,0 +1,381 @@
+-- Legacy MySQL core schema snapshot
+-- Source: job5c_2025_03_14.sql
+
+-- Table `board_albaguin`
+CREATE TABLE `board_albaguin` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `bbs_name` varchar(30) NOT NULL DEFAULT '',
+  `bbs_pass` varchar(30) NOT NULL DEFAULT '',
+  `bbs_email` varchar(100) NOT NULL DEFAULT '',
+  `bbs_title` varchar(100) NOT NULL DEFAULT '',
+  `bbs_img` varchar(50) NOT NULL DEFAULT '',
+  `bbs_review` text NOT NULL,
+  `bbs_count` int(11) NOT NULL DEFAULT '0',
+  `bbs_date` datetime DEFAULT NULL,
+  `groups` int(11) NOT NULL DEFAULT '0',
+  `seq` int(11) NOT NULL DEFAULT '0',
+  `depth` int(11) NOT NULL DEFAULT '0',
+  `bbs_etc1` varchar(100) NOT NULL DEFAULT '',
+  `bbs_etc2` int(5) NOT NULL DEFAULT '0',
+  `bbs_etc3` varchar(50) NOT NULL DEFAULT '',
+  `bbs_etc4` int(5) NOT NULL DEFAULT '0',
+  `bbs_etc5` varchar(50) NOT NULL DEFAULT '',
+  `bbs_attach2` varchar(100) NOT NULL DEFAULT '',
+  `bbs_attach3` varchar(100) NOT NULL DEFAULT '',
+  `bbs_etc6` varchar(100) NOT NULL DEFAULT '',
+  `bbs_etc7` varchar(100) NOT NULL DEFAULT '',
+  `phone` varchar(150) NOT NULL DEFAULT '',
+  `hphone` varchar(150) NOT NULL DEFAULT '',
+  `address` varchar(100) NOT NULL DEFAULT '',
+  `zip` varchar(100) NOT NULL DEFAULT '',
+  `select1` varchar(100) NOT NULL DEFAULT '0',
+  `select2` varchar(100) NOT NULL DEFAULT '0',
+  `select3` varchar(100) NOT NULL DEFAULT '',
+  `radio1` varchar(100) NOT NULL DEFAULT '',
+  `radio2` varchar(100) NOT NULL DEFAULT '',
+  `radio3` varchar(100) NOT NULL DEFAULT '',
+  `text1` varchar(100) NOT NULL DEFAULT '',
+  `text2` varchar(100) NOT NULL DEFAULT '',
+  `text3` varchar(100) NOT NULL DEFAULT '',
+  `gou_number` varchar(50) NOT NULL DEFAULT '',
+  `delivery` int(10) NOT NULL DEFAULT '0',
+  `money_in` int(10) NOT NULL DEFAULT '0',
+  `total_price` int(100) NOT NULL DEFAULT '0',
+  `b_category` varchar(150) NOT NULL DEFAULT '',
+  `reply_stats` int(1) NOT NULL DEFAULT '0',
+  `write_ip` varchar(100) NOT NULL DEFAULT '',
+  `org_writer` varchar(100) NOT NULL DEFAULT '',
+  `view_lock` int(1) NOT NULL DEFAULT '0',
+  `notice` int(1) NOT NULL DEFAULT '0',
+  `bbs_id` varchar(200) NOT NULL DEFAULT '',
+  `startdate` date NOT NULL DEFAULT '0000-00-00',
+  `enddate` date NOT NULL DEFAULT '0000-00-00',
+  `barcolor` varchar(20) NOT NULL DEFAULT '',
+  `fontcolor` varchar(20) NOT NULL DEFAULT '',
+  `guin_wait` int(1) NOT NULL DEFAULT '0',
+  `com_license` varchar(250) NOT NULL,
+  `admin_review` text NOT NULL,
+  `admin_return_reason` text NOT NULL,
+  `review_start_date` datetime NOT NULL,
+  `review_end_date` datetime NOT NULL,
+  PRIMARY KEY (`number`),
+  KEY `bbs_name` (`bbs_name`),
+  KEY `bbs_title` (`bbs_title`),
+  KEY `select1` (`select1`),
+  KEY `select2` (`select2`),
+  KEY `groups` (`groups`),
+  KEY `seq` (`seq`),
+  KEY `b_category` (`b_category`),
+  KEY `org_writer` (`org_writer`),
+  KEY `gou_number` (`gou_number`),
+  KEY `bbs_id` (`bbs_id`)
+) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;
+
+-- Table `job_com_guin`
+CREATE TABLE `job_com_guin` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `guin_number` int(11) NOT NULL DEFAULT '0',
+  `doc_number` int(11) NOT NULL DEFAULT '0',
+  `doc_id` varchar(150) NOT NULL DEFAULT '',
+  `doc_name` varchar(30) NOT NULL DEFAULT '',
+  `nowType` int(11) NOT NULL DEFAULT '0',
+  `answer1` text NOT NULL,
+  `answer2` text NOT NULL,
+  `answer3` text NOT NULL,
+  `answer4` text NOT NULL,
+  `answer5` text NOT NULL,
+  PRIMARY KEY (`number`)
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
+
+-- Table `job_com_guin_per`
+CREATE TABLE `job_com_guin_per` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `pNumber` int(11) NOT NULL DEFAULT '0',
+  `cNumber` int(11) NOT NULL DEFAULT '0',
+  `com_id` varchar(150) NOT NULL DEFAULT '',
+  `per_id` varchar(150) NOT NULL DEFAULT '',
+  `com_name` varchar(150) NOT NULL DEFAULT '',
+  `per_name` varchar(20) NOT NULL DEFAULT '',
+  `interview` text NOT NULL,
+  `read_ok` enum('Y','N') NOT NULL DEFAULT 'N',
+  `doc_ok` enum('Y','N') NOT NULL DEFAULT 'N',
+  `regdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `file1` varchar(250) NOT NULL DEFAULT '',
+  `file2` varchar(250) NOT NULL DEFAULT '',
+  `file3` varchar(250) NOT NULL DEFAULT '',
+  `file4` varchar(250) NOT NULL DEFAULT '',
+  `file5` varchar(250) NOT NULL DEFAULT '',
+  `secure` varchar(250) NOT NULL DEFAULT '',
+  `online_stats` int(1) NOT NULL DEFAULT '0',
+  `company_number` int(11) NOT NULL DEFAULT '0',
+  `email_stats` tinyint(1) NOT NULL DEFAULT '0',
+  `point` int(11) NOT NULL DEFAULT '0',
+  `memo` text NOT NULL,
+  `app_im` enum('Y','N') NOT NULL DEFAULT 'N',
+  PRIMARY KEY (`number`),
+  KEY `pNumber` (`pNumber`),
+  KEY `com_id` (`com_id`),
+  KEY `per_id` (`per_id`),
+  KEY `cNumber` (`cNumber`),
+  KEY `company_number` (`company_number`)
+) ENGINE=MyISAM AUTO_INCREMENT=124 DEFAULT CHARSET=utf8;
+
+-- Table `job_com_guin_per_log`
+CREATE TABLE `job_com_guin_per_log` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `bNumber` int(11) NOT NULL DEFAULT '0',
+  `regdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `online_stats` int(1) NOT NULL DEFAULT '0',
+  `pNumber` int(11) NOT NULL DEFAULT '0',
+  `cNumber` int(11) NOT NULL DEFAULT '0',
+  `com_id` varchar(150) NOT NULL DEFAULT '',
+  `per_id` varchar(150) NOT NULL DEFAULT '',
+  PRIMARY KEY (`number`),
+  KEY `bNumber` (`bNumber`)
+) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;
+
+-- Table `job_guin`
+CREATE TABLE `job_guin` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `guin_id` varchar(150) NOT NULL DEFAULT '',
+  `guin_com_name` varchar(30) NOT NULL DEFAULT '',
+  `guin_wait` int(1) DEFAULT '0',
+  `si1` int(5) NOT NULL DEFAULT '0',
+  `si2` int(5) NOT NULL DEFAULT '0',
+  `si3` int(5) NOT NULL DEFAULT '0',
+  `gu1` int(5) NOT NULL DEFAULT '0',
+  `gu2` int(5) NOT NULL DEFAULT '0',
+  `gu3` int(5) NOT NULL DEFAULT '0',
+  `gu1_ori` int(11) NOT NULL DEFAULT '0',
+  `gu2_ori` int(11) NOT NULL DEFAULT '0',
+  `gu3_ori` int(11) NOT NULL DEFAULT '0',
+  `type1` int(5) NOT NULL DEFAULT '0',
+  `type2` int(5) NOT NULL DEFAULT '0',
+  `type3` int(5) NOT NULL DEFAULT '0',
+  `type_sub1` int(5) NOT NULL DEFAULT '0',
+  `type_sub2` int(5) NOT NULL DEFAULT '0',
+  `type_sub3` int(5) NOT NULL DEFAULT '0',
+  `guin_name` varchar(50) NOT NULL DEFAULT '',
+  `guin_phone` varchar(30) NOT NULL DEFAULT '',
+  `guin_fax` varchar(30) NOT NULL DEFAULT '',
+  `guin_email` varchar(50) NOT NULL DEFAULT '',
+  `guin_homepage` varchar(100) NOT NULL DEFAULT '',
+  `guin_method` varchar(50) NOT NULL DEFAULT '',
+  `guin_type` varchar(50) NOT NULL DEFAULT '',
+  `guin_gender` varchar(30) NOT NULL DEFAULT '',
+  `guin_age` int(11) NOT NULL DEFAULT '0',
+  `guin_pay` int(11) DEFAULT '0',
+  `guin_pay_type` varchar(50) NOT NULL DEFAULT '',
+  `guin_pay_unit` varchar(50) DEFAULT '원',
+  `guin_pay_after` enum('y','n') NOT NULL DEFAULT 'n',
+  `guin_edu` varchar(50) NOT NULL DEFAULT '',
+  `guin_career` varchar(50) NOT NULL DEFAULT '',
+  `guin_career_year` varchar(30) NOT NULL DEFAULT '',
+  `guin_end_date` date NOT NULL DEFAULT '0000-00-00',
+  `guin_title` varchar(100) NOT NULL DEFAULT '',
+  `guin_work_content` varchar(100) NOT NULL DEFAULT '',
+  `guin_main` text NOT NULL,
+  `guin_count` int(11) NOT NULL DEFAULT '0',
+  `guin_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `guin_view_end_date` date NOT NULL DEFAULT '0000-00-00',
+  `guin_choongwon` int(1) NOT NULL DEFAULT '0',
+  `guin_etc2` varchar(50) NOT NULL DEFAULT '',
+  `pick` varchar(10) NOT NULL DEFAULT '',
+  `guin_modify` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `guin_etc5` varchar(50) NOT NULL DEFAULT '',
+  `guin_woodae` text NOT NULL,
+  `guin_grade` varchar(50) NOT NULL DEFAULT '',
+  `guin_lang` varchar(50) NOT NULL DEFAULT '',
+  `guin_license` varchar(200) NOT NULL DEFAULT '',
+  `guin_interview` text NOT NULL,
+  `guin_bokri` text NOT NULL,
+  `guin_banner1` int(10) NOT NULL DEFAULT '0',
+  `guin_banner2` int(10) NOT NULL DEFAULT '0',
+  `guin_banner3` int(10) NOT NULL DEFAULT '0',
+  `guin_bold` int(10) NOT NULL DEFAULT '0',
+  `guin_list_hyung` int(10) NOT NULL DEFAULT '0',
+  `guin_pick` int(10) NOT NULL DEFAULT '0',
+  `guin_ticker` int(10) NOT NULL DEFAULT '0',
+  `img1` varchar(100) NOT NULL DEFAULT '',
+  `img2` varchar(100) NOT NULL DEFAULT '',
+  `img3` varchar(100) NOT NULL DEFAULT '',
+  `img4` varchar(100) NOT NULL DEFAULT '',
+  `img5` varchar(100) NOT NULL DEFAULT '',
+  `img_text1` varchar(250) NOT NULL DEFAULT '',
+  `img_text2` varchar(250) NOT NULL DEFAULT '',
+  `img_text3` varchar(250) NOT NULL DEFAULT '',
+  `img_text4` varchar(250) NOT NULL DEFAULT '',
+  `img_text5` varchar(250) NOT NULL DEFAULT '',
+  `howpeople` varchar(250) NOT NULL DEFAULT '',
+  `howjoin` varchar(250) NOT NULL DEFAULT '',
+  `keyword` varchar(250) NOT NULL DEFAULT '',
+  `underground1` int(11) NOT NULL DEFAULT '0',
+  `underground2` int(11) NOT NULL DEFAULT '0',
+  `guin_bgcolor_com` int(10) NOT NULL DEFAULT '0',
+  `freeicon_com` varchar(100) NOT NULL DEFAULT '',
+  `freeicon_comDate` int(10) NOT NULL DEFAULT '0',
+  `work_day` varchar(20) NOT NULL DEFAULT '',
+  `start_worktime` varchar(20) NOT NULL DEFAULT '',
+  `finish_worktime` varchar(20) NOT NULL DEFAULT '',
+  `guinperson` varchar(30) NOT NULL DEFAULT '',
+  `guineducation` varchar(30) NOT NULL DEFAULT '',
+  `guinnational` varchar(30) NOT NULL DEFAULT '',
+  `guinsicompany` varchar(10) NOT NULL DEFAULT '',
+  `guin_uryo1` int(10) NOT NULL DEFAULT '0',
+  `guin_uryo2` int(10) NOT NULL DEFAULT '0',
+  `guin_uryo3` int(10) NOT NULL DEFAULT '0',
+  `guin_uryo4` int(10) NOT NULL DEFAULT '0',
+  `guin_uryo5` int(10) NOT NULL DEFAULT '0',
+  `use_adult` int(1) NOT NULL DEFAULT '0',
+  `HopeSize` varchar(50) NOT NULL DEFAULT '',
+  `subway_txt` varchar(200) NOT NULL DEFAULT '',
+  `marriage_chk` varchar(10) NOT NULL DEFAULT '',
+  `work_week` varchar(255) NOT NULL DEFAULT '',
+  `user_zip` varchar(10) NOT NULL DEFAULT '',
+  `user_addr1` varchar(150) NOT NULL DEFAULT '',
+  `user_addr2` varchar(250) NOT NULL DEFAULT '',
+  `x_point` float(12,9) NOT NULL DEFAULT '0.000000000',
+  `y_point` float(12,9) NOT NULL DEFAULT '0.000000000',
+  `x_point2` int(11) NOT NULL DEFAULT '0',
+  `y_point2` int(11) NOT NULL DEFAULT '0',
+  `x_do` int(11) NOT NULL DEFAULT '0',
+  `x_min` int(11) NOT NULL DEFAULT '0',
+  `x_sec` float(10,7) NOT NULL DEFAULT '0.0000000',
+  `y_do` int(11) NOT NULL DEFAULT '0',
+  `y_min` int(11) NOT NULL DEFAULT '0',
+  `y_sec` float(10,7) NOT NULL DEFAULT '0.0000000',
+  `photo2` varchar(250) NOT NULL DEFAULT '',
+  `photo3` varchar(250) NOT NULL DEFAULT '',
+  `boss_name` varchar(30) NOT NULL DEFAULT '',
+  `com_open_year` varchar(20) NOT NULL DEFAULT '',
+  `com_worker_cnt` varchar(20) NOT NULL DEFAULT '',
+  `com_profile1` text NOT NULL,
+  `company_number` int(11) NOT NULL DEFAULT '0',
+  `guin_bgcolor_select` varchar(10) NOT NULL DEFAULT '',
+  `inquiry_use` enum('y','n') NOT NULL DEFAULT 'n',
+  `regist_mobile` enum('y','n') NOT NULL DEFAULT 'n',
+  `com_license` varchar(250) NOT NULL,
+  `admin_review` text NOT NULL,
+  `admin_return_reason` text NOT NULL,
+  `review_start_date` datetime NOT NULL,
+  `review_end_date` datetime NOT NULL,
+  PRIMARY KEY (`number`),
+  KEY `guin_etc3` (`pick`),
+  KEY `guin_id` (`guin_id`),
+  KEY `guin_banner1` (`guin_banner1`,`guin_banner2`,`guin_banner3`,`guin_bold`,`guin_list_hyung`,`guin_pick`,`guin_ticker`),
+  KEY `guin_end_date` (`guin_end_date`),
+  KEY `guin_choongwon` (`guin_choongwon`),
+  KEY `si1` (`si1`),
+  KEY `si2` (`si2`),
+  KEY `si3` (`si3`),
+  KEY `gu1` (`gu1`),
+  KEY `gu2` (`gu2`),
+  KEY `gu3` (`gu3`),
+  KEY `type1` (`type1`),
+  KEY `type2` (`type2`),
+  KEY `type3` (`type3`),
+  KEY `type_sub1` (`type_sub1`),
+  KEY `type_sub2` (`type_sub2`),
+  KEY `type_sub3` (`type_sub3`),
+  KEY `si1_2` (`si1`,`si2`,`si3`),
+  KEY `gu1_2` (`gu1`,`gu2`,`gu3`),
+  KEY `type1_2` (`type1`,`type2`,`type3`),
+  KEY `type_sub1_2` (`type_sub1`,`type_sub2`,`type_sub3`),
+  KEY `underground1` (`underground1`),
+  KEY `underground2` (`underground2`),
+  KEY `guin_type` (`guin_type`),
+  KEY `guin_career` (`guin_career`),
+  KEY `company_number` (`company_number`),
+  KEY `gu1_ori` (`gu1_ori`),
+  KEY `gu2_ori` (`gu2_ori`),
+  KEY `gu3_ori` (`gu3_ori`),
+  KEY `guin_date` (`guin_date`),
+  KEY `guin_banner2` (`guin_banner2`),
+  KEY `guin_list_hyung` (`guin_list_hyung`),
+  KEY `guin_banner3` (`guin_banner3`),
+  KEY `guin_pick` (`guin_pick`),
+  KEY `guin_wait` (`guin_wait`)
+) ENGINE=MyISAM AUTO_INCREMENT=159 DEFAULT CHARSET=utf8;
+
+-- Table `job_guin_detail_view_log`
+CREATE TABLE `job_guin_detail_view_log` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `guin_number` int(11) NOT NULL DEFAULT '0',
+  `user_id` varchar(200) NOT NULL,
+  `user_ip` varchar(30) NOT NULL,
+  `log_date` datetime NOT NULL,
+  PRIMARY KEY (`number`),
+  KEY `guin_number` (`guin_number`),
+  KEY `log_date` (`log_date`)
+) ENGINE=MyISAM AUTO_INCREMENT=986 DEFAULT CHARSET=utf8;
+
+-- Table `job_guin_jump`
+CREATE TABLE `job_guin_jump` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `id` varchar(150) NOT NULL DEFAULT '',
+  `id_number` int(11) NOT NULL DEFAULT '0',
+  `guin_number` int(11) NOT NULL DEFAULT '0',
+  `guin_title` varchar(100) NOT NULL DEFAULT '',
+  `guin_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `reg_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  PRIMARY KEY (`number`),
+  KEY `id` (`id`),
+  KEY `guin_number` (`guin_number`)
+) ENGINE=MyISAM AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;
+
+-- Table `job_guin_stats`
+CREATE TABLE `job_guin_stats` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `guin_number` int(10) NOT NULL DEFAULT '0',
+  `guzic_id` varchar(150) NOT NULL DEFAULT '',
+  `view_check` int(1) NOT NULL DEFAULT '0',
+  `jiwon` int(1) NOT NULL DEFAULT '0',
+  `scrap` int(1) NOT NULL DEFAULT '0',
+  `pre_pass` int(1) NOT NULL DEFAULT '0',
+  `etc1` varchar(50) NOT NULL DEFAULT '',
+  `etc2` varchar(50) NOT NULL DEFAULT '',
+  `etc3` varchar(50) NOT NULL DEFAULT '',
+  `reg_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  PRIMARY KEY (`number`),
+  KEY `guin_number` (`guin_number`),
+  KEY `guzic_id` (`guzic_id`),
+  KEY `view_check` (`view_check`),
+  KEY `scrap` (`scrap`),
+  KEY `pre_pass` (`pre_pass`),
+  KEY `jiwon` (`jiwon`)
+) ENGINE=MyISAM DEFAULT CHARSET=utf8;
+
+-- Table `job_per_guin_view`
+CREATE TABLE `job_per_guin_view` (
+  `number` int(11) NOT NULL AUTO_INCREMENT,
+  `per_id` varchar(150) NOT NULL DEFAULT '',
+  `guin_number` int(11) NOT NULL DEFAULT '0',
+  PRIMARY KEY (`number`),
+  KEY `per_id` (`per_id`),
+  KEY `guin_number` (`guin_number`)
+) ENGINE=MyISAM AUTO_INCREMENT=36 DEFAULT CHARSET=utf8;
+
+-- Table `point_jangboo`
+CREATE TABLE `point_jangboo` (
+  `number` int(10) NOT NULL AUTO_INCREMENT,
+  `id` varchar(150) NOT NULL DEFAULT '',
+  `point` varchar(40) NOT NULL DEFAULT '',
+  `pay_type` varchar(255) NOT NULL DEFAULT '',
+  `in_check` int(1) NOT NULL DEFAULT '0',
+  `or_no` varchar(50) NOT NULL DEFAULT '',
+  `links_number` int(10) NOT NULL DEFAULT '0',
+  `links_title` varchar(100) NOT NULL DEFAULT '',
+  `reg_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
+  `gou_number` varchar(50) NOT NULL DEFAULT '',
+  `product_stats` varchar(20) NOT NULL DEFAULT '',
+  `result_check` varchar(20) NOT NULL DEFAULT '',
+  `member_type` int(1) NOT NULL DEFAULT '1',
+  `banking_name` varchar(100) NOT NULL DEFAULT '',
+  `pg_response_code` varchar(30) NOT NULL DEFAULT '',
+  `pg_response_msg` varchar(100) NOT NULL DEFAULT '',
+  PRIMARY KEY (`number`),
+  KEY `or_no` (`or_no`),
+  KEY `id` (`id`),
+  KEY `banking_name` (`banking_name`)
+) ENGINE=MyISAM AUTO_INCREMENT=453 DEFAULT CHARSET=utf8;
+
