diff --git a/db/_legacy/schema.core.pg.sql b/db/_legacy/schema.core.pg.sql
new file mode 100644
index 0000000000000000000000000000000000000000..46f0d3e099e0e6dec83ded82a1892947a7f9efcd
--- /dev/null
+++ b/db/_legacy/schema.core.pg.sql
@@ -0,0 +1,385 @@
+-- Canonical PostgreSQL core schema
+-- Derived from job5c_2025_03_14.sql
+
+CREATE TYPE yn_flag AS ENUM ('Y', 'N');
+CREATE TYPE yn_lower_flag AS ENUM ('y', 'n');
+
+-- Table "board_albaguin"
+CREATE TABLE "board_albaguin" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "bbs_name" VARCHAR(30) DEFAULT '' NOT NULL,
+  "bbs_pass" VARCHAR(30) DEFAULT '' NOT NULL,
+  "bbs_email" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_title" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_img" VARCHAR(50) DEFAULT '' NOT NULL,
+  "bbs_review" TEXT NOT NULL,
+  "bbs_count" INTEGER DEFAULT 0 NOT NULL,
+  "bbs_date" TIMESTAMPTZ,
+  "groups" INTEGER DEFAULT 0 NOT NULL,
+  "seq" INTEGER DEFAULT 0 NOT NULL,
+  "depth" INTEGER DEFAULT 0 NOT NULL,
+  "bbs_etc1" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_etc2" INTEGER DEFAULT 0 NOT NULL,
+  "bbs_etc3" VARCHAR(50) DEFAULT '' NOT NULL,
+  "bbs_etc4" INTEGER DEFAULT 0 NOT NULL,
+  "bbs_etc5" VARCHAR(50) DEFAULT '' NOT NULL,
+  "bbs_attach2" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_attach3" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_etc6" VARCHAR(100) DEFAULT '' NOT NULL,
+  "bbs_etc7" VARCHAR(100) DEFAULT '' NOT NULL,
+  "phone" VARCHAR(150) DEFAULT '' NOT NULL,
+  "hphone" VARCHAR(150) DEFAULT '' NOT NULL,
+  "address" VARCHAR(100) DEFAULT '' NOT NULL,
+  "zip" VARCHAR(100) DEFAULT '' NOT NULL,
+  "select1" VARCHAR(100) DEFAULT '0' NOT NULL,
+  "select2" VARCHAR(100) DEFAULT '0' NOT NULL,
+  "select3" VARCHAR(100) DEFAULT '' NOT NULL,
+  "radio1" VARCHAR(100) DEFAULT '' NOT NULL,
+  "radio2" VARCHAR(100) DEFAULT '' NOT NULL,
+  "radio3" VARCHAR(100) DEFAULT '' NOT NULL,
+  "text1" VARCHAR(100) DEFAULT '' NOT NULL,
+  "text2" VARCHAR(100) DEFAULT '' NOT NULL,
+  "text3" VARCHAR(100) DEFAULT '' NOT NULL,
+  "gou_number" VARCHAR(50) DEFAULT '' NOT NULL,
+  "delivery" INTEGER DEFAULT 0 NOT NULL,
+  "money_in" INTEGER DEFAULT 0 NOT NULL,
+  "total_price" INTEGER DEFAULT 0 NOT NULL,
+  "b_category" VARCHAR(150) DEFAULT '' NOT NULL,
+  "reply_stats" INTEGER DEFAULT 0 NOT NULL,
+  "write_ip" VARCHAR(100) DEFAULT '' NOT NULL,
+  "org_writer" VARCHAR(100) DEFAULT '' NOT NULL,
+  "view_lock" INTEGER DEFAULT 0 NOT NULL,
+  "notice" INTEGER DEFAULT 0 NOT NULL,
+  "bbs_id" VARCHAR(200) DEFAULT '' NOT NULL,
+  "startdate" DATE NOT NULL,
+  "enddate" DATE NOT NULL,
+  "barcolor" VARCHAR(20) DEFAULT '' NOT NULL,
+  "fontcolor" VARCHAR(20) DEFAULT '' NOT NULL,
+  "guin_wait" INTEGER DEFAULT 0 NOT NULL,
+  "com_license" VARCHAR(250) NOT NULL,
+  "admin_review" TEXT NOT NULL,
+  "admin_return_reason" TEXT NOT NULL,
+  "review_start_date" TIMESTAMPTZ NOT NULL,
+  "review_end_date" TIMESTAMPTZ NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_com_guin"
+CREATE TABLE "job_com_guin" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "guin_number" INTEGER DEFAULT 0 NOT NULL,
+  "doc_number" INTEGER DEFAULT 0 NOT NULL,
+  "doc_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "doc_name" VARCHAR(30) DEFAULT '' NOT NULL,
+  "nowType" INTEGER DEFAULT 0 NOT NULL,
+  "answer1" TEXT NOT NULL,
+  "answer2" TEXT NOT NULL,
+  "answer3" TEXT NOT NULL,
+  "answer4" TEXT NOT NULL,
+  "answer5" TEXT NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_com_guin_per"
+CREATE TABLE "job_com_guin_per" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "pNumber" INTEGER DEFAULT 0 NOT NULL,
+  "cNumber" INTEGER DEFAULT 0 NOT NULL,
+  "com_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "per_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "com_name" VARCHAR(150) DEFAULT '' NOT NULL,
+  "per_name" VARCHAR(20) DEFAULT '' NOT NULL,
+  "interview" TEXT NOT NULL,
+  "read_ok" yn_flag DEFAULT 'N' NOT NULL,
+  "doc_ok" yn_flag DEFAULT 'N' NOT NULL,
+  "regdate" TIMESTAMPTZ NOT NULL,
+  "file1" VARCHAR(250) DEFAULT '' NOT NULL,
+  "file2" VARCHAR(250) DEFAULT '' NOT NULL,
+  "file3" VARCHAR(250) DEFAULT '' NOT NULL,
+  "file4" VARCHAR(250) DEFAULT '' NOT NULL,
+  "file5" VARCHAR(250) DEFAULT '' NOT NULL,
+  "secure" VARCHAR(250) DEFAULT '' NOT NULL,
+  "online_stats" INTEGER DEFAULT 0 NOT NULL,
+  "company_number" INTEGER DEFAULT 0 NOT NULL,
+  "email_stats" BOOLEAN DEFAULT FALSE NOT NULL,
+  "point" INTEGER DEFAULT 0 NOT NULL,
+  "memo" TEXT NOT NULL,
+  "app_im" yn_flag DEFAULT 'N' NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_com_guin_per_log"
+CREATE TABLE "job_com_guin_per_log" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "bNumber" INTEGER DEFAULT 0 NOT NULL,
+  "regdate" TIMESTAMPTZ NOT NULL,
+  "online_stats" INTEGER DEFAULT 0 NOT NULL,
+  "pNumber" INTEGER DEFAULT 0 NOT NULL,
+  "cNumber" INTEGER DEFAULT 0 NOT NULL,
+  "com_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "per_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_guin"
+CREATE TABLE "job_guin" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "guin_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "guin_com_name" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guin_wait" INTEGER DEFAULT 0,
+  "si1" INTEGER DEFAULT 0 NOT NULL,
+  "si2" INTEGER DEFAULT 0 NOT NULL,
+  "si3" INTEGER DEFAULT 0 NOT NULL,
+  "gu1" INTEGER DEFAULT 0 NOT NULL,
+  "gu2" INTEGER DEFAULT 0 NOT NULL,
+  "gu3" INTEGER DEFAULT 0 NOT NULL,
+  "gu1_ori" INTEGER DEFAULT 0 NOT NULL,
+  "gu2_ori" INTEGER DEFAULT 0 NOT NULL,
+  "gu3_ori" INTEGER DEFAULT 0 NOT NULL,
+  "type1" INTEGER DEFAULT 0 NOT NULL,
+  "type2" INTEGER DEFAULT 0 NOT NULL,
+  "type3" INTEGER DEFAULT 0 NOT NULL,
+  "type_sub1" INTEGER DEFAULT 0 NOT NULL,
+  "type_sub2" INTEGER DEFAULT 0 NOT NULL,
+  "type_sub3" INTEGER DEFAULT 0 NOT NULL,
+  "guin_name" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_phone" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guin_fax" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guin_email" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_homepage" VARCHAR(100) DEFAULT '' NOT NULL,
+  "guin_method" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_type" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_gender" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guin_age" INTEGER DEFAULT 0 NOT NULL,
+  "guin_pay" INTEGER DEFAULT 0,
+  "guin_pay_type" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_pay_unit" VARCHAR(50) DEFAULT '원',
+  "guin_pay_after" yn_lower_flag DEFAULT 'n' NOT NULL,
+  "guin_edu" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_career" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_career_year" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guin_end_date" DATE NOT NULL,
+  "guin_title" VARCHAR(100) DEFAULT '' NOT NULL,
+  "guin_work_content" VARCHAR(100) DEFAULT '' NOT NULL,
+  "guin_main" TEXT NOT NULL,
+  "guin_count" INTEGER DEFAULT 0 NOT NULL,
+  "guin_date" TIMESTAMPTZ NOT NULL,
+  "guin_view_end_date" DATE NOT NULL,
+  "guin_choongwon" INTEGER DEFAULT 0 NOT NULL,
+  "guin_etc2" VARCHAR(50) DEFAULT '' NOT NULL,
+  "pick" VARCHAR(10) DEFAULT '' NOT NULL,
+  "guin_modify" TIMESTAMPTZ NOT NULL,
+  "guin_etc5" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_woodae" TEXT NOT NULL,
+  "guin_grade" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_lang" VARCHAR(50) DEFAULT '' NOT NULL,
+  "guin_license" VARCHAR(200) DEFAULT '' NOT NULL,
+  "guin_interview" TEXT NOT NULL,
+  "guin_bokri" TEXT NOT NULL,
+  "guin_banner1" INTEGER DEFAULT 0 NOT NULL,
+  "guin_banner2" INTEGER DEFAULT 0 NOT NULL,
+  "guin_banner3" INTEGER DEFAULT 0 NOT NULL,
+  "guin_bold" INTEGER DEFAULT 0 NOT NULL,
+  "guin_list_hyung" INTEGER DEFAULT 0 NOT NULL,
+  "guin_pick" INTEGER DEFAULT 0 NOT NULL,
+  "guin_ticker" INTEGER DEFAULT 0 NOT NULL,
+  "img1" VARCHAR(100) DEFAULT '' NOT NULL,
+  "img2" VARCHAR(100) DEFAULT '' NOT NULL,
+  "img3" VARCHAR(100) DEFAULT '' NOT NULL,
+  "img4" VARCHAR(100) DEFAULT '' NOT NULL,
+  "img5" VARCHAR(100) DEFAULT '' NOT NULL,
+  "img_text1" VARCHAR(250) DEFAULT '' NOT NULL,
+  "img_text2" VARCHAR(250) DEFAULT '' NOT NULL,
+  "img_text3" VARCHAR(250) DEFAULT '' NOT NULL,
+  "img_text4" VARCHAR(250) DEFAULT '' NOT NULL,
+  "img_text5" VARCHAR(250) DEFAULT '' NOT NULL,
+  "howpeople" VARCHAR(250) DEFAULT '' NOT NULL,
+  "howjoin" VARCHAR(250) DEFAULT '' NOT NULL,
+  "keyword" VARCHAR(250) DEFAULT '' NOT NULL,
+  "underground1" INTEGER DEFAULT 0 NOT NULL,
+  "underground2" INTEGER DEFAULT 0 NOT NULL,
+  "guin_bgcolor_com" INTEGER DEFAULT 0 NOT NULL,
+  "freeicon_com" VARCHAR(100) DEFAULT '' NOT NULL,
+  "freeicon_comDate" INTEGER DEFAULT 0 NOT NULL,
+  "work_day" VARCHAR(20) DEFAULT '' NOT NULL,
+  "start_worktime" VARCHAR(20) DEFAULT '' NOT NULL,
+  "finish_worktime" VARCHAR(20) DEFAULT '' NOT NULL,
+  "guinperson" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guineducation" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guinnational" VARCHAR(30) DEFAULT '' NOT NULL,
+  "guinsicompany" VARCHAR(10) DEFAULT '' NOT NULL,
+  "guin_uryo1" INTEGER DEFAULT 0 NOT NULL,
+  "guin_uryo2" INTEGER DEFAULT 0 NOT NULL,
+  "guin_uryo3" INTEGER DEFAULT 0 NOT NULL,
+  "guin_uryo4" INTEGER DEFAULT 0 NOT NULL,
+  "guin_uryo5" INTEGER DEFAULT 0 NOT NULL,
+  "use_adult" INTEGER DEFAULT 0 NOT NULL,
+  "HopeSize" VARCHAR(50) DEFAULT '' NOT NULL,
+  "subway_txt" VARCHAR(200) DEFAULT '' NOT NULL,
+  "marriage_chk" VARCHAR(10) DEFAULT '' NOT NULL,
+  "work_week" VARCHAR(255) DEFAULT '' NOT NULL,
+  "user_zip" VARCHAR(10) DEFAULT '' NOT NULL,
+  "user_addr1" VARCHAR(150) DEFAULT '' NOT NULL,
+  "user_addr2" VARCHAR(250) DEFAULT '' NOT NULL,
+  "x_point" NUMERIC(12,9) DEFAULT 0.000000000 NOT NULL,
+  "y_point" NUMERIC(12,9) DEFAULT 0.000000000 NOT NULL,
+  "x_point2" INTEGER DEFAULT 0 NOT NULL,
+  "y_point2" INTEGER DEFAULT 0 NOT NULL,
+  "x_do" INTEGER DEFAULT 0 NOT NULL,
+  "x_min" INTEGER DEFAULT 0 NOT NULL,
+  "x_sec" NUMERIC(10,7) DEFAULT 0.0000000 NOT NULL,
+  "y_do" INTEGER DEFAULT 0 NOT NULL,
+  "y_min" INTEGER DEFAULT 0 NOT NULL,
+  "y_sec" NUMERIC(10,7) DEFAULT 0.0000000 NOT NULL,
+  "photo2" VARCHAR(250) DEFAULT '' NOT NULL,
+  "photo3" VARCHAR(250) DEFAULT '' NOT NULL,
+  "boss_name" VARCHAR(30) DEFAULT '' NOT NULL,
+  "com_open_year" VARCHAR(20) DEFAULT '' NOT NULL,
+  "com_worker_cnt" VARCHAR(20) DEFAULT '' NOT NULL,
+  "com_profile1" TEXT NOT NULL,
+  "company_number" INTEGER DEFAULT 0 NOT NULL,
+  "guin_bgcolor_select" VARCHAR(10) DEFAULT '' NOT NULL,
+  "inquiry_use" yn_lower_flag DEFAULT 'n' NOT NULL,
+  "regist_mobile" yn_lower_flag DEFAULT 'n' NOT NULL,
+  "com_license" VARCHAR(250) NOT NULL,
+  "admin_review" TEXT NOT NULL,
+  "admin_return_reason" TEXT NOT NULL,
+  "review_start_date" TIMESTAMPTZ NOT NULL,
+  "review_end_date" TIMESTAMPTZ NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_guin_detail_view_log"
+CREATE TABLE "job_guin_detail_view_log" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "guin_number" INTEGER DEFAULT 0 NOT NULL,
+  "user_id" VARCHAR(200) NOT NULL,
+  "user_ip" VARCHAR(30) NOT NULL,
+  "log_date" TIMESTAMPTZ NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_guin_jump"
+CREATE TABLE "job_guin_jump" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "id_number" INTEGER DEFAULT 0 NOT NULL,
+  "guin_number" INTEGER DEFAULT 0 NOT NULL,
+  "guin_title" VARCHAR(100) DEFAULT '' NOT NULL,
+  "guin_date" TIMESTAMPTZ NOT NULL,
+  "reg_date" TIMESTAMPTZ NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_guin_stats"
+CREATE TABLE "job_guin_stats" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "guin_number" INTEGER DEFAULT 0 NOT NULL,
+  "guzic_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "view_check" INTEGER DEFAULT 0 NOT NULL,
+  "jiwon" INTEGER DEFAULT 0 NOT NULL,
+  "scrap" INTEGER DEFAULT 0 NOT NULL,
+  "pre_pass" INTEGER DEFAULT 0 NOT NULL,
+  "etc1" VARCHAR(50) DEFAULT '' NOT NULL,
+  "etc2" VARCHAR(50) DEFAULT '' NOT NULL,
+  "etc3" VARCHAR(50) DEFAULT '' NOT NULL,
+  "reg_date" TIMESTAMPTZ NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "job_per_guin_view"
+CREATE TABLE "job_per_guin_view" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "per_id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "guin_number" INTEGER DEFAULT 0 NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Table "point_jangboo"
+CREATE TABLE "point_jangboo" (
+  "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
+  "id" VARCHAR(150) DEFAULT '' NOT NULL,
+  "point" VARCHAR(40) DEFAULT '' NOT NULL,
+  "pay_type" VARCHAR(255) DEFAULT '' NOT NULL,
+  "in_check" INTEGER DEFAULT 0 NOT NULL,
+  "or_no" VARCHAR(50) DEFAULT '' NOT NULL,
+  "links_number" INTEGER DEFAULT 0 NOT NULL,
+  "links_title" VARCHAR(100) DEFAULT '' NOT NULL,
+  "reg_date" TIMESTAMPTZ NOT NULL,
+  "gou_number" VARCHAR(50) DEFAULT '' NOT NULL,
+  "product_stats" VARCHAR(20) DEFAULT '' NOT NULL,
+  "result_check" VARCHAR(20) DEFAULT '' NOT NULL,
+  "member_type" INTEGER DEFAULT 1 NOT NULL,
+  "banking_name" VARCHAR(100) DEFAULT '' NOT NULL,
+  "pg_response_code" VARCHAR(30) DEFAULT '' NOT NULL,
+  "pg_response_msg" VARCHAR(100) DEFAULT '' NOT NULL,
+  PRIMARY KEY ("number")
+);
+
+-- Indexes
+CREATE INDEX "board_albaguin_bbs_name" ON "board_albaguin" (bbs_name);
+CREATE INDEX "board_albaguin_bbs_title" ON "board_albaguin" (bbs_title);
+CREATE INDEX "board_albaguin_select1" ON "board_albaguin" (select1);
+CREATE INDEX "board_albaguin_select2" ON "board_albaguin" (select2);
+CREATE INDEX "board_albaguin_groups" ON "board_albaguin" (groups);
+CREATE INDEX "board_albaguin_seq" ON "board_albaguin" (seq);
+CREATE INDEX "board_albaguin_b_category" ON "board_albaguin" (b_category);
+CREATE INDEX "board_albaguin_org_writer" ON "board_albaguin" (org_writer);
+CREATE INDEX "board_albaguin_gou_number" ON "board_albaguin" (gou_number);
+CREATE INDEX "board_albaguin_bbs_id" ON "board_albaguin" (bbs_id);
+CREATE INDEX "job_com_guin_per_pNumber" ON "job_com_guin_per" (pNumber);
+CREATE INDEX "job_com_guin_per_com_id" ON "job_com_guin_per" (com_id);
+CREATE INDEX "job_com_guin_per_per_id" ON "job_com_guin_per" (per_id);
+CREATE INDEX "job_com_guin_per_cNumber" ON "job_com_guin_per" (cNumber);
+CREATE INDEX "job_com_guin_per_company_number" ON "job_com_guin_per" (company_number);
+CREATE INDEX "job_com_guin_per_log_bNumber" ON "job_com_guin_per_log" (bNumber);
+CREATE INDEX "job_guin_guin_etc3" ON "job_guin" (pick);
+CREATE INDEX "job_guin_guin_id" ON "job_guin" (guin_id);
+CREATE INDEX "job_guin_guin_banner1" ON "job_guin" (guin_banner1, guin_banner2, guin_banner3, guin_bold, guin_list_hyung, guin_pick, guin_ticker);
+CREATE INDEX "job_guin_guin_end_date" ON "job_guin" (guin_end_date);
+CREATE INDEX "job_guin_guin_choongwon" ON "job_guin" (guin_choongwon);
+CREATE INDEX "job_guin_si1" ON "job_guin" (si1);
+CREATE INDEX "job_guin_si2" ON "job_guin" (si2);
+CREATE INDEX "job_guin_si3" ON "job_guin" (si3);
+CREATE INDEX "job_guin_gu1" ON "job_guin" (gu1);
+CREATE INDEX "job_guin_gu2" ON "job_guin" (gu2);
+CREATE INDEX "job_guin_gu3" ON "job_guin" (gu3);
+CREATE INDEX "job_guin_type1" ON "job_guin" (type1);
+CREATE INDEX "job_guin_type2" ON "job_guin" (type2);
+CREATE INDEX "job_guin_type3" ON "job_guin" (type3);
+CREATE INDEX "job_guin_type_sub1" ON "job_guin" (type_sub1);
+CREATE INDEX "job_guin_type_sub2" ON "job_guin" (type_sub2);
+CREATE INDEX "job_guin_type_sub3" ON "job_guin" (type_sub3);
+CREATE INDEX "job_guin_si1_2" ON "job_guin" (si1, si2, si3);
+CREATE INDEX "job_guin_gu1_2" ON "job_guin" (gu1, gu2, gu3);
+CREATE INDEX "job_guin_type1_2" ON "job_guin" (type1, type2, type3);
+CREATE INDEX "job_guin_type_sub1_2" ON "job_guin" (type_sub1, type_sub2, type_sub3);
+CREATE INDEX "job_guin_underground1" ON "job_guin" (underground1);
+CREATE INDEX "job_guin_underground2" ON "job_guin" (underground2);
+CREATE INDEX "job_guin_guin_type" ON "job_guin" (guin_type);
+CREATE INDEX "job_guin_guin_career" ON "job_guin" (guin_career);
+CREATE INDEX "job_guin_company_number" ON "job_guin" (company_number);
+CREATE INDEX "job_guin_gu1_ori" ON "job_guin" (gu1_ori);
+CREATE INDEX "job_guin_gu2_ori" ON "job_guin" (gu2_ori);
+CREATE INDEX "job_guin_gu3_ori" ON "job_guin" (gu3_ori);
+CREATE INDEX "job_guin_guin_date" ON "job_guin" (guin_date);
+CREATE INDEX "job_guin_guin_banner2" ON "job_guin" (guin_banner2);
+CREATE INDEX "job_guin_guin_list_hyung" ON "job_guin" (guin_list_hyung);
+CREATE INDEX "job_guin_guin_banner3" ON "job_guin" (guin_banner3);
+CREATE INDEX "job_guin_guin_pick" ON "job_guin" (guin_pick);
+CREATE INDEX "job_guin_guin_wait" ON "job_guin" (guin_wait);
+CREATE INDEX "job_guin_detail_view_log_guin_number" ON "job_guin_detail_view_log" (guin_number);
+CREATE INDEX "job_guin_detail_view_log_log_date" ON "job_guin_detail_view_log" (log_date);
+CREATE INDEX "job_guin_jump_id" ON "job_guin_jump" (id);
+CREATE INDEX "job_guin_jump_guin_number" ON "job_guin_jump" (guin_number);
+CREATE INDEX "job_guin_stats_guin_number" ON "job_guin_stats" (guin_number);
+CREATE INDEX "job_guin_stats_guzic_id" ON "job_guin_stats" (guzic_id);
+CREATE INDEX "job_guin_stats_view_check" ON "job_guin_stats" (view_check);
+CREATE INDEX "job_guin_stats_scrap" ON "job_guin_stats" (scrap);
+CREATE INDEX "job_guin_stats_pre_pass" ON "job_guin_stats" (pre_pass);
+CREATE INDEX "job_guin_stats_jiwon" ON "job_guin_stats" (jiwon);
+CREATE INDEX "job_per_guin_view_per_id" ON "job_per_guin_view" (per_id);
+CREATE INDEX "job_per_guin_view_guin_number" ON "job_per_guin_view" (guin_number);
+CREATE INDEX "point_jangboo_or_no" ON "point_jangboo" (or_no);
+CREATE INDEX "point_jangboo_id" ON "point_jangboo" (id);
+CREATE INDEX "point_jangboo_banking_name" ON "point_jangboo" (banking_name);
