#!/usr/bin/env node
/**
 * ChatGPT Code Review Script
 *
 * PR의 변경사항을 분석하고 ChatGPT를 통해 코드 리뷰를 수행합니다.
 *
 * Environment Variables:
 * - CHATGPT_API_KEY: OpenAI API key (required)
 * - PR_NUMBER: Pull request number
 * - PR_TITLE: Pull request title
 * - PR_AUTHOR: Pull request author
 * - BASE_BRANCH: Base branch name
 * - HEAD_BRANCH: Head branch name
 * - FILES_COUNT: Number of changed files
 * - ADDITIONS: Number of added lines
 * - DELETIONS: Number of deleted lines
 */

import { readFile, writeFile } from 'fs/promises';
import { existsSync } from 'fs';

const CHATGPT_API_URL = 'https://api.openai.com/v1/chat/completions';
const CHATGPT_MODEL = 'gpt-4o';  // 또는 'gpt-4-turbo', 'gpt-3.5-turbo'

/**
 * ChatGPT API 호출
 */
async function callChatGPT(messages, temperature = 0.3) {
  const apiKey = process.env.CHATGPT_API_KEY;

  if (!apiKey) {
    throw new Error('CHATGPT_API_KEY environment variable is required');
  }

  const response = await fetch(CHATGPT_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: CHATGPT_MODEL,
      messages,
      temperature,
      max_tokens: 4000,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`ChatGPT API error: ${response.status} ${error}`);
  }

  const data = await response.json();
  return data.choices[0].message.content;
}

/**
 * 7-Phase Code Review 수행
 */
async function performCodeReview(prInfo, changedFiles) {
  console.log('Starting 7-Phase Code Review...');

  // 변경 내용 요약
  const filesSummary = changedFiles.map(f =>
    `- ${f.filename} (${f.status}): +${f.additions} -${f.deletions}`
  ).join('\n');

  // 패치 내용 (diff) 준비
  const patchContent = changedFiles
    .filter(f => f.patch)
    .slice(0, 10)  // 최대 10개 파일만 (토큰 제한)
    .map(f => `File: ${f.filename}\n\`\`\`diff\n${f.patch}\n\`\`\``)
    .join('\n\n');

  // ChatGPT에게 전달할 프롬프트
  const systemPrompt = `You are an expert code reviewer performing a systematic 7-phase review.
Be thorough but constructive. Focus on:
- Code quality and best practices
- Security vulnerabilities
- Performance issues
- Test coverage
- Documentation
- Maintainability

Format your response in the following structure:
## Phase 1: Scope & Intent
## Phase 2: File-by-File Analysis
## Phase 3: Integration Points
## Phase 4: Testing & Coverage
## Phase 5: Documentation
## Phase 6: Security & Performance
## Phase 7: Best Practices

## Final Verdict
- Verdict: APPROVE | REQUEST_CHANGES | COMMENT
- Critical Issues: [list]
- Recommendations: [list]`;

  const userPrompt = `Please review this Pull Request:

**PR #${prInfo.number}: ${prInfo.title}**
Author: ${prInfo.author}
Branch: ${prInfo.headBranch} → ${prInfo.baseBranch}

**Changes Summary:**
- ${prInfo.filesCount} files changed
- +${prInfo.additions} -${prInfo.deletions} lines

**Files Changed:**
${filesSummary}

**Code Changes (Diff):**
${patchContent}

Please perform a comprehensive 7-phase review and provide your verdict.`;

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt }
  ];

  const reviewContent = await callChatGPT(messages);

  console.log('Review completed!');
  return reviewContent;
}

/**
 * 리뷰 결과 파싱 및 verdict 추출
 */
function parseReviewResult(reviewContent) {
  // Verdict 추출
  let verdict = 'COMMENT';  // 기본값

  if (reviewContent.includes('Verdict: APPROVE') ||
      reviewContent.includes('Final Verdict: APPROVE')) {
    verdict = 'APPROVE';
  } else if (reviewContent.includes('Verdict: REQUEST_CHANGES') ||
             reviewContent.includes('Final Verdict: REQUEST_CHANGES') ||
             reviewContent.includes('REQUEST CHANGES')) {
    verdict = 'REQUEST_CHANGES';
  }

  // 요약 생성
  const summary = `# 🤖 ChatGPT Code Review

${reviewContent}

---

*Generated by ChatGPT Code Review Bot*
*Model: ${CHATGPT_MODEL}*
`;

  return {
    verdict,
    summary,
    inline_comments: []  // 향후 확장: 특정 라인에 대한 코멘트
  };
}

/**
 * Main
 */
async function main() {
  try {
    // PR 정보 수집
    const prInfo = {
      number: process.env.PR_NUMBER || 'unknown',
      title: process.env.PR_TITLE || 'Unknown PR',
      author: process.env.PR_AUTHOR || 'unknown',
      baseBranch: process.env.BASE_BRANCH || 'main',
      headBranch: process.env.HEAD_BRANCH || 'unknown',
      filesCount: parseInt(process.env.FILES_COUNT || '0'),
      additions: parseInt(process.env.ADDITIONS || '0'),
      deletions: parseInt(process.env.DELETIONS || '0'),
    };

    console.log('PR Info:', prInfo);

    // 변경된 파일 정보 읽기
    if (!existsSync('changed-files.json')) {
      throw new Error('changed-files.json not found');
    }

    const changedFiles = JSON.parse(await readFile('changed-files.json', 'utf8'));
    console.log(`Reviewing ${changedFiles.length} files...`);

    // 너무 큰 PR은 경고
    if (changedFiles.length > 50 || prInfo.additions + prInfo.deletions > 2000) {
      console.warn('⚠️ Large PR detected. Review might be incomplete.');
      console.warn('Recommendation: Split into smaller PRs for better review quality.');
    }

    // 코드 리뷰 수행
    const reviewContent = await performCodeReview(prInfo, changedFiles);

    // 결과 파싱
    const result = parseReviewResult(reviewContent);

    // 결과 저장
    await writeFile('chatgpt-review-result.json', JSON.stringify(result, null, 2));

    console.log('✅ Review completed successfully');
    console.log('Verdict:', result.verdict);

    process.exit(0);
  } catch (error) {
    console.error('❌ Review failed:', error.message);
    console.error(error.stack);

    // 실패 시에도 기본 코멘트 생성
    const fallbackResult = {
      verdict: 'COMMENT',
      summary: `# ⚠️ ChatGPT Code Review Failed

An error occurred during automated review:
\`\`\`
${error.message}
\`\`\`

Please perform manual review.`,
      inline_comments: []
    };

    await writeFile('chatgpt-review-result.json', JSON.stringify(fallbackResult, null, 2));

    process.exit(1);
  }
}

main();
